### PR TITLE
Don't compress git files in caravel and mgmt_core_wrapper repos

### PR DESCRIPTION
**Pull request by antonblanchard**
make compress is trying to compress a large file in mgmt_core_wrapper
.git dir.

### CODE REVIEW

**Comment by d-m-bailey** [comment]
@antonblanchard This pull request modifies 3 files. Is that what you intended? I think the main repo may have been updated after you created the branch. Maybe fetch upstream on github and then in your local repo
```
git fetch main
git pull main
git merge main
git push
```
Maybe.

**Comment by antonblanchard** [comment]
It's some automated script that is getting applied to all of my PRs post creation:
```
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run creating manifest
        run: make manifest
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Run creating README.rst
        run: make README.rst
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic changes to Manifest and README.rst
          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
```

**Comment by antonblanchard** [comment]
Looking at this closer, I think the issue is the caravel `make install` installs the mgmt engine into caravel_user_project/ instead of caravel_user_project/caravel/ if MCW_ROOT is not set

**Review by RTimothyEdwards — CHANGES_REQUESTED** [review]
The fix for the `Makefile` is proper, but please make sure that your pull request does not include changes to `README.rst` (which overwrites a typo fix from Mitch) or `manifest` (which is auto-generated).

**Comment by antonblanchard** [comment]
@RTimothyEdwards Thanks for the review, I've rebased and the other files are now not getting updated.

FYI The issue is an automated script on pull request creation, and your recent commit just undid the typo:

https://github.com/efabless/caravel/commit/8aafe0cff6f8e48ce944fda189d764639c5e3d02#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fL155

**Comment by RTimothyEdwards** [comment]
@antonblanchard :  There is some automatic script that changes the manifest but also changes the README.rst and so undermines any attempt to fix the typo in that file. . .  It automatically puts the typo back in.

**Review by RTimothyEdwards — APPROVED** [review]
Critically needed fix.

**Comment by RTimothyEdwards** [comment]
@jeffdi :  Please merge this ASAP.  Hopefully it does not cause conflicts with changes to the Makefile in other pull requests.

**Pull request merged**
