### PR TITLE
fix set_user_id.py to move viali correctly

### LINKED ISSUE #74: set_user_id.py script moves via's incorrectly
1) the script changes the mag file for all shapes at the target coordinate (not just `viali`).
2) moving `viali` can cause a metal1 hole.
user_id_programming_no_via

To reproduce, from `caravel_user_project`
```
export USER_ID="A0B1C2D3"
make set_user_id
```
Check the `mag/user_id_programming.mag` file.

### PR DESCRIPTION
**Pull request by d-m-bailey**
1) Only moves the first target coordinate (`viali`)
1) Adds `metal1` at old target location

Result
user_id_fix

Fixes #74

### CODE REVIEW

**Review by RTimothyEdwards — COMMENTED** [review]
This is unnecessary;  I made a change (as I said I would) to the .mag file that fixes the issue.

**Comment by d-m-bailey** [comment]
Great! Did you handle the problem of the `via1` at the same position as the `viali` being moved also?

**Comment by RTimothyEdwards** [comment]
It should solve that problem.  However, I looked at the layout file and realize that there is a similar issue now with local interconnect having the same coordinates as the viali, which it shouldn't, which I think is an unintended consequence of something I did in magic recently. . .

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  Never mind my comment above;  it's a non-issue.

**Pull request closed without merging**
