### PR TITLE
Restructuring housekeeping spi FSM

### PR DESCRIPTION
**Pull request by mo-hosni**
[NouranAbdelaziz](https://github.com/NouranAbdelaziz): "Restructuring the housekeeping spi FSM to be more clean so that each always block handle only one register and there is no register updated in more than one always block."

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
@mo-hosni :  Do not merge changes to my code that I have not reviewed.  I still do not understand the intent of this change, and certain comments like "each always block handle[s] only one register" make no sense (each always block already handled a unique set of registers).  There are multiple modes of operation of the SPI for N-byte register reads and writes and stream reads and writes, which have never been properly incorporated into a testbench.  How are you guaranteeing that this change does not break the existing implementation?

**Comment by mo-hosni** [comment]
@RTimothyEdwards 

That's not the main branch. This is a devolvement branch where we try new things.

I merged the changes to this branch to try them. I actually too do not know the intent of these changes.

I did a housekeeping implementation using the changes and will report the results. @M0stafaRady is also doing RTL/GL verification on this branch. 

Neither Mostafa or I can decide what to be merged to main. We don't even have the permission to do so.

**Comment by mo-hosni** [comment]
@shalan @NouranAbdelaziz

**Comment by shalan** [comment]
@RTimothyEdwards We are merging to a development branch as @mo-hosni mentioned earlier. These changes are related to housekeeping code refactoring. Code refactoring will be followed by changes to address the CDC issues in the housekeeping.

**Comment by M0stafaRady** [comment]
@RTimothyEdwards  
Just an update about the spi testbench, we have cocotb tests for writing and reading stream ,N-bytes and user_pass_thru. There is still no test yet for mgmt_pass_thru.

**Comment by RTimothyEdwards** [comment]
@shalan :  You still need a link to an issue and a project, and documentation on what is being changed, and why.  It is not clear to me at all why these changes are needed or how it addresses the CDC issues.

**Pull request merged**
