### PR TITLE
Chip io fix ports

### PR DESCRIPTION
**Pull request by RTimothyEdwards**
Fixes the .mag, LEF, DEF, and GDS views of `chip_io` and `chip_io_alt`, which were missing some of the power pins.  The pin labels got accidentally erased during layout re-work.

This pull request fixes issue #174

### CODE REVIEW

**Comment by kareefardi** [comment]
I am closing this until the target branch is `caravel_redesign`. We wouldn't want this to be accidentally merged into main

**Comment by kareefardi** [comment]
@RTimothyEdwards can you change the target branch and reopen the PR ?

**Comment by RTimothyEdwards** [comment]
@kareefardi :  I thought I should be able to change the target but it won't let me---maybe because it's closed?  I'm going to re-open and try to change it.  If I can't, I'll close it again and redo the pull request.

**Comment by RTimothyEdwards** [comment]
@kareefardi :  I can't change the target now so I will close again and re-do this.

**Pull request closed without merging**
