### PR TITLE
Changes to enable chip_io LVS with magic/netgen.

### PR DESCRIPTION
**Pull request by d-m-bailey**

### CODE REVIEW

**Review by RTimothyEdwards — COMMENTED** [review]
Can you please make the changes to `sky130_fd_io.spice` and `sky130_ef_io.spice` a pull request for the open_pdks repository?  And can the caravel and chip_io modifications be made in the magic source?  Because neither of the caravel or chip_io GDS files are used, and they shouldn't even be in the repository.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards Working with a more recent version of magic, eliminated the need for SUBCUT around the io pads. So currently there are 3->4 types of changes to the io pads that I've incorporated.
1. Fixed the DIODE recognition layer to not cover `tap` layers in `sky130_fd_io__gnd2gnd_120x2_lv_isosub`
2. Remove extraneous node division layers in `sky130_fd_io__res250only_small`. `met1/short`x2, `li1/short`x2, `poly/short`x3, `poly/cut`x4.
3. Remove `met1/short`x2 from `sky130_fd_io__signal_5_sym_hv_local_5term`. Very small donuts. Maybe used to differentiate source and drain?
4. (new) Added met3/short devices to separate VSSIO - VSSIO_Q, VDDIO - VDDIO_Q in `sky130_ef_io__vssio_hvc_clamped_pad` and `sky130_ef_io__vddio_hvc_clamped_pad`

The spice modifications reflect the above changes. I can't find the original `mag` data for these cells, but I'll keep looking.

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  The "original" .mag files are from the open_pdks installation.  They are generated by reading GDS and writing magic, but where that produces errors, I have scripts in open_pdks to patch things up.  Regardless, the change needs to be made in the open_pdks repository.

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  I do also have the ability to swap in corrected GDS files in open_pdks, which I am currently doing for several digital standard cells that have DRC errors in the original sources.

**Comment by d-m-bailey** [comment]
I'm proposing layout changes to the following cells,
```
sky130_fd_io__res250only_small
sky130_fd_io__signal_5_sym_hv_local_5term
sky130_fd_io__gnd2gnd_sub_dnwl
sky130_fd_io__gnd2gnd_120x2_lv_isosub
sky130_ef_io__vssio_hvc_clamped_pad
sky130_ef_io__vddio_hvc_clamped_pad
```
The addition of met3/short layers at the parent hierarchy in the clamped_pad cells will necessitate flattening during extraction.
Haven't found the source for the sky130_fd_io mag cells yet.
On the spice side, it looks like if need to modify the sky130_ef_io.cdl file to have the changes appear in the pdk sky130_ef_io.spice file. Still looking for the source of the sky130_fd_io.spice data.

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  The source of `sky130_fd_io.spice` is open_pdks, under `sky130/custom/sky130_fd_io/spice/`.  The original was not in the skywater-pdk repository because it contained errors.  I worked out the problems and posted the corrected netlists to open_pdks.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards I made an open_pdks PR for the netlist changes. Probably take a day or two to figure out where the original layout changes need to be made. To pass LVS, I modified the final caravel gds.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards The layout changes aren't going to be as simple as I'd hoped.
The following cells have mag files with gds links, so I assume they're generated from gds.
```
sky130_fd_io__res250only_small
sky130_fd_io__signal_5_sym_hv_local_5term
sky130_fd_io__gnd2gnd_120x2_lv_isosub
```
(Previously, I'd wanted to change `sky130_fd_io__gnd2gnd_sub_dnwl` too, but that's not strictly necessary. The changes can be made to `sky130_fd_io__gnd2gnd_120x2_lv_isosub`)
Looks like the source gds for these cells may be reused in several different io pads and merged into one library before the mag files are created. One solution is for me to create individually modified gds for these cells and create a PR with them in `sky130/custom/sky130_fd_io/gds` but currently all the files in that directory are prefixed with `sky130_ef_io` and I don't believe it's feasible to rename them (you'd have to change multiple parent cells). After that, you would need to figure out how to integrate them into the pdk (they need to override the old gds).

The following cells have no gds links in the mag data, and in order to separate VSSIO/VSSIO_Q and VDDIO/VDDIO_Q in magic, you'd need to modify a subcell which is unfortunately also used in other cells and gds based.
```
sky130_ef_io__vssio_hvc_pad
sky130_ef_io__vssio_hvc_clamped_pad
sky130_ef_io__vddio_hvc_pad
sky130_ef_io__vddio_hvc_clamped_pad
```
In gds, I add the met3/short layers at the top level and then flatten the subcells when reading the gds before magic extraction. I could copy the shared gds based subcell to new cell (e.g. `sky130_fd_io__top_ground_hvc_wpad` -> `sky130_ef_io__top_vssio_hvc_wpad`), add the met3/short in gds and then change the reference in the top magic cell. This would mean pull requests for `sky130/custom/sky130_fd_io/gds/sky130_ef_io.gds` libraries and the individual `sky130/custom/sky130_fd_io/mag/*` files. 

Since both the gds and the mag files exist in the `sky130/custom` directory, is there a possibility of a problem if the data is not in sync?

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  All .mag views in the PDK that come from foundry sources (such as the I/O library) just point back to the original GDS file.  While magic does extraction from its own view that is derived from reading the GDS, when it writes GDS it pulls the original vendor source.  You can make changes that affect extraction to the .mag files, which can be done in the open_pdks Makefile.  This may make more sense than modifying the GDS.

If you need to make changes to the `sky130_ef_io` GDS or .mag files, I can get you a tarball of my sources and the instructions for generating the files that end up in open_pdks.  What I've been doing is to generate GDS and then copy both the .mag and .gds files to my open_pdks repository, so it should be possible to get that GDS file from those .mag files.  But I should probably just move my other files and instructions into open_pdks;  it's not like it's much overhead.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards We're getting closer, but I don't think we're quite on the same page yet.

My ultimate goal is to be able to run LVS on the caravel/cararvan gds - i.e., the exact data that is used to create the masks. Because I don't reference any of the mag cells in the pdk, the changes to the foundry i/o either need to be done on the original gds or in magic after reading in the gds but before extraction. One problem is that I'm flattening all the cells beneath the io cells when I read in the gds, so I can't won't be able to make changes at the subcell level. 
Is it possible to read in subcells, modify the mag versions and then flatten (possibly several hierarchies) before extraction with a script?

Also, can you send me the tarball of `sky130_ef_io` gds and mag files with instructions?

**Comment by d-m-bailey** [comment]
Here are the changes I propose.

1. `sky130_fd_io__gnd2gnd_120x2_lv_isosub` Change DIODE `81/23` layer
before
gnd2gnd_120x2_lv_isosub_before

after removing DIODE `81/23` from `sky130_fd_io__gnd2gnd_120x2_lv_isosub` and copying diff `65/20` to `81/23` in `sky130_fd_io__gnd2gnd_sub_dnwl`
gnd2gnd_120x2_lv_isosub_after

2. `sky130_fd_io__res250only_small` Remove extraneous resistor recognition layers 
res250_poly-cut

remove 3 (all) poly/cut `66/14`
res250_li-short

remove 2 (all) li/short `67/15`
res250_met1-short

remove 2 (all) met1/short `68/15`
res250_poly-res

remove 4 poly/res `66/13` (2 on each side between licon) leave middle.
final (note layer color change)
res250_final

3. `sky130_fd_io__signal_5_sym_hv_local_5term` Remove 2 (all) very small donut met1/short `68/15`.
5term

4. `sky130_ef_io__vssio_hvc_clamped_pad` add 4 met3/short `70/15` above and below VSSIO_Q
vssio_hvc

5. `sky130_ef_io__vddio_hvc_clamped_pad` add 4 met3/short `70/15` above and below VDDIO_Q
vddio_hvc

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  I have been staring at the metal3 short solution for separating VDDIO_Q and VSSIO_Q, and I don't see how it works.  There is a solid piece of metal3 underneath in cell `sky130_fd_io__top_ground_hvc_wpad` that would short any metal resistor when extracting.  The only solution that I can see would work is to narrow down the VSSIO_Q labels in several cells so that the labels don't overlap any contacts.  There are other solutions that can be done in the magic view but which would not work for extracting from a design reading it all from GDS unless you applied the changes to the magic view every time.  But it would work for extracting a design from magic's top level.

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  I have been staring at the metal3 short solution for separating VDDIO_Q and VSSIO_Q, and I don't see how it works.  There is a solid piece of metal3 underneath in cell `sky130_fd_io__top_ground_hvc_wpad` that would short any metal resistor when extracting.  The only solution that I can see would work is to narrow down the VSSIO_Q labels in several cells so that the labels don't overlap any contacts.  There are other solutions that can be done in the magic view but which would not work for extracting from a design reading it all from GDS unless you applied the changes to the magic view every time.  But it would work for extracting a design from magic's top level.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards I'm not absolutely sure how magic handles cifin/cifout, but it appears to me that while within magic, since `met3` and `rm3` are on the same plane, they can not overlap, on cifout, `MET3` is `allm3` (the OR of `met3` and `rm3`). Conversely, on cifin, `m3` is `MET3` and-not `MET3RES`, so they are separated here. My LVS setup flattens all the gds subcells of the I/O cells before extracting, so having `MET3RES` in the top cell appears to work with `MET3` in the lower cells.

**Comment by RTimothyEdwards** [comment]
PR marked with label "wrong repo", mainly to categorize it as something, and partly to note that many of the contents require changes in the PDK rather than caravel.

**Comment by RTimothyEdwards** [comment]
New issues are going to be generated in open_pdks.  I am closing this issue here.

**Pull request closed without merging**
