### PR TITLE
Some modifications related to the use of params

### PR DESCRIPTION
**Pull request by ax3ghazy**
- chip_io and mprj_io: switch to a parameter defaulting at 38
- mem_wb: size the synthesized memory using MEM_WORDS

---------------------------------------------------------------------------------------------
An alternative would be to create a "defs.v" to be included in other files.

### CODE REVIEW

**Comment by ax3ghazy** [comment]
I just ran into another issue caused by default parameters.

> An alternative would be to create a "defs.v" to be included in other files.

This is safer, having all information in one place... I will do this instead; please don't merge this PR yet.

**Comment by RTimothyEdwards** [comment]
I will wait for your instruction on what to do with this. . .

**Comment by ax3ghazy** [comment]
@RTimothyEdwards: This is now ready; could you have a look?

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me.

**Pull request merged**
