### PR TITLE
Fix the simple_por to (logically) isolate the 1.8V and 3.3V grounds.

### PR DESCRIPTION
**Pull request by RTimothyEdwards**
This commit does the following:
(1) Corrects the xschem simple_por schematic to separate the 1.8V and 3.3V grounds.
(2) Corrects the xschem simple_por symbol to separate the 1.8V and 3.3V grounds.
(3) Corrects the xschem testbench to connect to both grounds of simple_por.
(4) Corrects the simple_por layout to remove the 1.8V logic from the
    3.3V ground and connect it instead to the 1.8V ground.
(5) Extends the top-level power routing of caravel and caravan to
    make a better connection to the simple_por 1.8V ground.
(6) Adds an LVS script to properly check the simple_por layout against the
    xschem-generated schematic netlist.

NOTE: None of these modifications change the function of any circuit.  The
1.8V and 3.3V ground nets are only logically separated in the netlists but
share the substrate.  This fix cleanly defines the 1.8V and 3.3V grounds
within the simple_por, where they were previously mingled.  It also ensures
that the full LVS for caravel and caravan can now include the simple_por at
the transistor level and still pass.

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  If you could please review, you are the most knowledgeable about the fix to the simple_por being implemented here.  I also took the step of correcting the xschem schematics (which still had just one "vss" pin) and writing a script to run LVS.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards From what I could tell, the following files look to be correctly updated.
```
mag/simple_por.mag
xschem/simple_por.spice
```
The following files did not appear to be changed.
```
gds/simple_por.gds
xschem/simple_por.sch
xschem/simple_por.sym
xschem/simple_por_tb.sch
xschem/simple_por_tb.sym
```
Didn't check the global routing.

**Comment by d-m-bailey** [comment]
@RTimothyEdwards From what I could tell, the following files look to be correctly updated.
```
mag/simple_por.mag
xschem/simple_por.spice
```
The following files did not appear to be changed.
```
gds/simple_por.gds
xschem/simple_por.sch
xschem/simple_por.sym
xschem/simple_por_tb.sch
xschem/simple_por_tb.sym
```
Didn't check the global routing.

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  I'm not sure what you're looking at.  The diff list under the "Files changed" tab clearly shows changes to all ten files.  BTW, the GDS is compressed, so the file is `gds/simple_por.gds.gz`, not `gds/simple_por.gds`.

**Comment by d-m-bailey** [comment]
I cloned the repo and used the `fix_simple_por` branch. Unfortunately, the xschem files I checked were from an older directory. Sorry for the confusion. The following files are ok as far as I can tell.
```
xschem/simple_por.sch
xschem/simple_por.sym
xschem/simple_por_tb.sch
xschem/simple_por_tb.sym
```
However, directly downloading from https://github.com/efabless/caravel/blob/fix_simple_por/gds/simple_por.gds.gz gives me the same results when viewed in klayout (metal4 not cut, no SUBCUT).

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  Thanks for pointing that out.  I had not removed GDS_FILE from the .mag file and so it just overwrote the GDS file with itself, which isn't very useful.

It would be awfully nice if git would include some meaningful diff of binary files.  Then it would be a lot easier to tell that only the timestamps had changed.  Although it would also have to recognize that the file is compressed. . .

I just pushed an update that replaces the GDS file with the new one (correctly, this time).

**Comment by d-m-bailey** [comment]
@RTimothyEdwards Is the gds file for `simple_por` necessary? If the mag file doesn't contain a pointer, won't it be unused?

**Comment by d-m-bailey** [comment]
GDS looks good too.

**Comment by RTimothyEdwards** [comment]
@d-m-bailey :  The idea behind using a pointer to the GDS file for simple_por is that the GDS for the caravel top level will be generated using the option settings `cif *hier write disable`, which avoids doing hierarchical processing of the GDS output to resolve issues with, say, wells or implant layers that are too closely spaced and need to be merged by bridging across the gap.  The hierarchical processing is time consuming and unnecessary for the kind of top-level assembly of pre-generated layouts that is done as the final step for the caravel and caravan chips.  However, custom layouts, especially analog ones like simple_por, are dependent on the hierarchical GDS processing.  So it's better to pre-generate the GDS (using hierarchical processing) and then just reference the GDS file during chip assembly.

**Review by jeffdi — APPROVED** [review]

**Pull request merged**
